CREATE TABLE PERSISTENT_LOGINS ( 
USERNAME             	VARCHAR(128) NOT NULL,
SERIES             	VARCHAR(64) NOT NULL,
TOKEN                     VARCHAR(64) NOT NULL,
LAST_USED             TIMESTAMP NOT NULL,
CONSTRAINT PK_PERSISTENT_LOGINS PRIMARY KEY(SERIES)
)

